#************************** DEV root level Makefile ***********************

make	=nmake

all:
	cd country
	$(make)
	cd ..\ansi
	del *.sys
	$(make)
	cd ..\keyboard
	$(make)
	cd ..\display
	$(make)
	cd ..\smartdrv
	$(make)
	cd ..\driver
	$(make)
	cd ..



